load loads.maude
mod TEST is
    pr UPLC-EXECUTOR .
endm
set print attribute on .

--- red generateMetaProgram("(program 1.0.0 [x x])") .
--- red processMetaProgram(generateMetaProgram("(program 1000.0045.03 (lam xc98aZ (con unit `(`))))")) .
red processMetaProgram(generateMetaProgram("(program 1000.0045.03 (lam x x))")) .
--- red uplc .
--- red in STRING : substr("#FFFF", 2, 1) .
--- red allVarCharAreValid("xc98aZ", 0) .
q